import MyNavbar from './Navbar';
import MyFooter from './Footer';
import Head from 'next/head';

export default function MyLayout({ children }) {
  return (
    <div className="layout">
      <Head>
        <title>TLMOTO</title>
        <meta name="description" content="Generated by Francisco & Jorge" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyNavbar />
      <div className="content">{children}</div>
      <MyFooter />
    </div>
  );
}
