import { useRef } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.scss"
import MySection from "../components/homePage/Home";
import MySectionVideo from "../components/homePage/HomeVideo";
import { aboutUsText, animatedNumbers, competitionText, prototypeText, whiteBoxText } from "@/components/textContent/HomeSectionTexts";

export default function Home() {
  const section1 = useRef();
  const section2 = useRef();
  const section3 = useRef();
  const section4 = useRef();
  const section5 = useRef();

  function scrollTo(section) {
    section.current.scrollIntoView({ behavior: "smooth" });
  }
  return (
    <div>
      <Head>
        <title>TLMOTO</title>
        <meta name="description" content="Generated by Francisco & Jorge" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`container ${styles.container}`}>
        <div ref={section1}>
          <MySectionVideo
            video={`/videos/intro_video_background.mp4`}
            goToSectionRef={section2}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={section2}>
          <MySection
            image={`/images/home/team_background.png`}
            headline={`ABOUT US`}
            animatedNumbers={animatedNumbers}
            text={aboutUsText}
            goToSectionRef={section3}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={section3}>
          <MySection
            image={`/images/home/aragon_background.jpg`}
            headline={`COMPETITIONS`}
            text={competitionText}
            buttons={[{ label: "MS"}, { label: "CNV"}, { label: "MEI"}]}
            whiteBox={whiteBoxText}
            goToSectionRef={section4}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={section4}>
          <MySection
            image={`/images/home/prototype_background.jpg`}
            headline={`PROTOTYPES`}
            text={prototypeText}
            buttons={[{ label: "LEARN MORE", href: "/garage" }]}
            goToSectionRef={section5}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={section5}>
          <MySection
            image={`/images/blue_black_background.webp`}
            secImage={`/images/home/sponsors_background.png`}
            scrollTo={scrollTo}
            showArrow={false}
          />
        </div>
      </div>
    </div>
  );
}